cd ~/selasphorus_evolution

##estimate SFS per species with angsd
~/angsd/angsd -b data/wgs/bamlists/rufus_males.txt -anc anhu_alignment/Canna_MUGM01_haploid.fa \
-dosaf 1 -remove_bads -unique_only -minMapQ 20 -minQ 20 -only_proper_pairs 1 -trim 0 \
-gl 1 -P 30 -out sfs_males/rufus 

~/angsd/angsd -b data/wgs/bamlists/sasin_sasin_males.txt -anc anhu_alignment/Canna_MUGM01_haploid.fa \
-dosaf 1 -remove_bads -unique_only -minMapQ 20 -minQ 20 -only_proper_pairs 1 -trim 0 \
-gl 1 -P 30 -out sfs_males/sasin_sasin 

~/angsd/angsd -b data/wgs/bamlists/sasin_sedentarius_males.txt -anc anhu_alignment/Canna_MUGM01_haploid.fa \
-dosaf 1 -remove_bads -unique_only -minMapQ 20 -minQ 20 -only_proper_pairs 1 -trim 0 \
-gl 1 -P 30 -out sfs_males/sasin_sedentarius 

~/angsd/angsd -b data/wgs/bamlists/calliope_males.txt -anc anhu_alignment/Canna_MUGM01_haploid.fa \
-dosaf 1 -remove_bads -unique_only -minMapQ 20 -minQ 20 -only_proper_pairs 1 -trim 0 \
-gl 1 -P 30 -out sfs_males/calliope 

/angsd/angsd -b data/wgs/bamlists/east_males.txt -anc anhu_alignment/Canna_MUGM01_haploid.fa \
-dosaf 1 -remove_bads -unique_only -minMapQ 20 -minQ 20 -only_proper_pairs 1 -trim 0 \
-gl 1 -P 30 -out sfs_males/east 

~/angsd/angsd -b data/wgs/bamlists/west_males.txt -anc anhu_alignment/Canna_MUGM01_haploid.fa \
-dosaf 1 -remove_bads -unique_only -minMapQ 20 -minQ 20 -only_proper_pairs 1 -trim 0 \
-gl 1 -P 30 -out sfs_males/west 

##estimate 2-d SFS (RAM req is ~ twice the total file size of the .saf.gz files generated by angsd -dosaf)
~/angsd/misc/realSFS sfs_males/rufus.saf.idx sfs_males/calliope.saf.idx -P 32 > sfs_males/ruf_cal.sfs

~/angsd/misc/realSFS sfs_males/rufus.saf.idx sfs_males/sasin_sasin.saf.idx -P 32 > sfs_males/ruf_sas.sfs

~/angsd/misc/realSFS sfs_males/rufus.saf.idx sfs_males/sasin_sedentarius.saf.idx -P 32 > sfs_males/ruf_sed.sfs

~/angsd/misc/realSFS sfs_males/sasin_sasin.saf.idx sfs_males/sasin_sedentarius.saf.idx -P 32 > sfs_males/sas_sed.sfs

~/angsd/misc/realSFS sfs_males/east.saf.idx sfs_males/west.saf.idx -P 32 > sfs_males/east_west.sfs

###Fst by SNP
#~/angsd/misc/realSFS fst index sfs_males/rufus.saf.idx sfs_males/calliope.saf.idx -sfs sfs_males/ruf_cal.sfs \
#-P 32 -whichFst 1 -fstout sfs_males/ruf_cal
#
#~/angsd/misc/realSFS fst index sfs_males/rufus.saf.idx sfs_males/sasin_sasin.saf.idx -sfs sfs_males/ruf_sas.sfs \
#-P 32 -whichFst 1 -fstout sfs_males/ruf_sas
#
#~/angsd/misc/realSFS fst index sfs_males/rufus.saf.idx sfs_males/sasin_sedentarius.saf.idx -sfs sfs_males/ruf_sed.sfs \
#-P 32 -whichFst 1 -fstout sfs_males/ruf_sed
#
#~/angsd/misc/realSFS fst index sfs_males/sasin_sasin.saf.idx sfs_males/sasin_sedentarius.saf.idx -sfs sfs_males/sas_sed.sfs \
#-P 32 -whichFst 1 -fstout sfs_males/sas_sed
#
#~/angsd/misc/realSFS fst index sfs_males/east.saf.idx sfs_males/west.saf.idx -sfs sfs_males/east_west.sfs \
#-P 32 -whichFst 1 -fstout sfs_males/east_west

##sliding-window Fst
~/angsd/misc/realSFS fst stats2 sfs_males/ruf_cal.fst.idx -P 32 -win 50000 \
-step 50000 > window_stats/ruf_cal_angsd_fstwindow.txt

~/angsd/misc/realSFS fst stats2 sfs_males/ruf_sas.fst.idx -P 32 -win 50000 \
-step 50000 > window_stats/ruf_sas_angsd_fstwindow.txt

~/angsd/misc/realSFS fst stats2 sfs_males/ruf_sed.fst.idx -P 32 -win 50000 \
-step 50000 > window_stats/ruf_sed_angsd_fstwindow.txt

~/angsd/misc/realSFS fst stats2 sfs_males/sas_sed.fst.idx -P 32 -win 50000 \
-step 50000 > window_stats/sas_sed_angsd_fstwindow.txt

~/angsd/misc/realSFS fst stats2 sfs_males/east_west.fst.idx -P 32 -win 50000 \
-step 50000 > window_stats/east_west_angsd_fstwindow.txt


